### ISSUE TITLE
Unable to configure project using bobcat-aem-bdd template

### ISSUE THREAD

**Issue by JasleenCh** [Cognifide/bobcat-gradle-template#4]
Please refer to the below screenshot for the failures and steps followed:

![screen shot 2018-05-14 at 21 37 04](https://user-images.githubusercontent.com/15213586/40022265-57d40e1a-57bf-11e8-8568-690b5b009971.png)

Can you please have a look.

**Comment by Danon9111** [comment]
Hi @JasleenCh 

I assume, looking on the screenshot,  you've stopped on 50% of generating project. Am I right? 

If yes please refer to updated version of [README](https://github.com/Cognifide/bobcat-gradle-template/blob/master/README.md) and make sure you have done all steps like it is described. 

In other case can you please provide more information, like what happened when you have done all steps like in mentioned document?

Best regards,
Andrzej

**Comment by kaczymuczy** [comment]
You have to provide the **group** name and then hit _ENTER_
Later you have to do the same for the **project** name and the **version** number
