### ISSUE TITLE
Generating a new template without providing a target directory creates a project directory with empty files

### ISSUE THREAD

**Issue by kaczymuczy** [Cognifide/bobcat-gradle-template#8]
`gradlew generate -i` or `gradlew generate -i -Ptemplate=ANY_TEMPLATE_NAME` creates a project directory with empty files (but the structure of the project is correct).

The same result is for `gradlew generate -i -Ptarget=generated -Ptemplate=ANY_TEMPLATE_NAME`

**Comment by mkrzyzanowski** [comment]
Fixed in #15
